safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: ru
default_body_class: list

author:
    name: Алексей Андросов
    # url:  http://example.com/
    company:
        name: Яндекс.Почта
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
